### PR TITLE
Trigger click topic event

### PR DESCRIPTION
**Pull request by alex-ju**
Trigger an event when clicking a topic item in the `MillerColumnsElement` so it can be tracked with analytics.

It can be used/tested as shown in the example below (updated after review):

```diff
-var millerColumns = document.querySelector('.miller-columns')
-
-millerColumns.addEventListener('click-topic', function(e){
-  console.log(e.detail.topicNames.join(' > '), e.detail.selected)
-})

+var millerColumnsInput = document.querySelector('.miller-columns input')
+
+millerColumnsInput.addEventListener('click', function(e){
+  console.log(e.target)
+})

```

[Trello card](https://trello.com/c/tAXP6pf1)

### CODE REVIEW

**Comment by benthorner** [comment]
I think we may have veered off what we were trying to achieve here. This might be me explaining/documenting it badly, so apologies if that's the case. My understanding of it: 

   - We'd like to use the existing 'Check' tag in GTM to track the Miller Columns checkboxes
   - Miller Columns doesn't actually let the user interact with the checkbox directly
   - We'd like to forward a 'click' event onto the checkbox when it's enclosing div is clicked

At the moment, it looks like we've gone down a route where we're firing a custom event on the Miller Columns element itself. This looks like it would work, but we'd need more code to support it in our app, since we'd like to detect when a user checks or unchecks a topic in the Miller Columns. If we do the above approach, we should get that for free with the existing GTM tag.

Let's have a chat about it when we're working on this again :-).

**Comment by alex-ju** [comment]
@benthorner: Updated to follow the approach you described.

**Comment by benthorner** [comment]
@alex-ju this looks good. As discussed, we've now got a more subtle problem related to where we're dispatching the event in the code: the 'topicClicked' function. Since this function is used externally, we can't guarantee that calls to this function actually represent a click event on the checkbox. One approach we could take to fix this would be to dispatch the event in the [individual click/keydown listeners](https://github.com/alphagov/miller-columns-element/blob/a1278ffc1473adb971f8ff48b80cd9991231ec99/index.js#L360).

**Comment by alex-ju** [comment]
@benthorner updated as discussed and added tests to cover selection for when pressing Enter or Space.

**Pull request merged**
